package com.app.messagealarm.model.entity

object ApplicationTable {
    const val TABLE_NAME = "applications_new"
    const val PACKAGE_NAME = "package_name"
    const val APP_NAME = "app_name"
    const val ID = "id"
    const val RUNNING_STATUS = "running_status"
    const val IS_ALARM_ENABLED = "_is_alarm_enabled"
    const val IS_SPEAK_ENABLED = "_is_speak_enabled"
    const val ALARM_REPEAT = "alarm_repeat"
    const val RINGTONE = "ringtone"
    const val VIBRATE_ON_ALARM = "vibrate_on_alarm"
    const val JUST_VIBRATE = "just_vibrate"
    const val CUSTOM_TIME = "custom_time"
    const val START_TIME = "start_time"
    const val END_TIME = "end_time"
    const val NUMBER_OF_PLAY = "number_of_play"
    const val SENDER_NAMES = "sender_names"
    const val MESSAGE_BODY = "message_body"
    const val REPEAT_DAYS = "repeat_days"
    const val TONE_PATH = "tone_path"
    const val BITMAP_PATH = "bitmap_path"
    const val IGNORED_NAMES = "ignored_names"
    const val SOUND_LEVEL = "sound_level"
    const val IS_FLASH_ON = "is_flash_on"
}
